---
title: Viktor Smári Ágústuson
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: viktorsmari@gmail.com
description: Viktor Smári Ágústuson, Computer Scientist.
baseurl: ''
url: http://viktorsmari.github.io
twitter_username: viktorsmar
github_username: viktorsmari
linkedin_username: viktorsmari
youtube_username: viktorsmari
future: true
markdown: kramdown
google_analytics: UA-51437669-1
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
